CREATE TABLE USUARIO(
	ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
	NOMBRE_USUARIO VARCHAR(100) NOT NULL UNIQUE,
	CONTRASENA VARCHAR(200) NOT NULL
);

CREATE TABLE PRODUCTO(
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(300) NULL,
	PRECIO DECIMAL(18, 2) NOT NULL CHECK (PRECIO >0),
	STOCK INTEGER NOT NULL CHECK (STOCK > 0),
	FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
	ESTADO VARCHAR(20) NOT NULL CHECK(ESTADO IN('Disponible', 'No disponible')),
	PESO DECIMAL(18,2) NULL
);

CREATE TABLE CLIENTE(
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR (100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	CORREO VARCHAR(200) NOT NULL UNIQUE,
	TELEFONO VARCHAR(20) NULL
);

SELECT * FROM USUARIO;
SELECT * FROM PRODUCTO;
SELECT * FROM CLIENTE;